services:
  - type: worker
    name: poster-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python poster.py
    envVars:
      - key: BOT_TOKEN
        sync: false   # или значение
      - key: GROQ_API_KEY
        sync: false
      - key: CHANNEL_ID
        value: "@rezumeizi"
